@startmindmap functions

* buaahungry
** 账号管理
*** 登录、注册、退出
*** 密码修改、头像修改
** 订餐(用户)
*** 浏览菜品
**** 选择食堂
**** 显示价格、评论、名字
*** 购物车
**** 添加、减少商品
**** 查看购物车
**** 结账、生成订单
** 订单(用户、配送员)
*** 查看未接收、配送中、已完成的订单
*** 取消未接收订单
*** 查看订单详情，包括地址、时间、菜品、数目、总价、配送人信息
*** 用户确认完成订单
** 评论
*** 查看菜品、食堂评论
*** 发表评论
*** 删除评论（管理员功能）
** 菜品管理(食堂)
*** 查看、下架、修改自己上传的菜品
*** 增加菜品
@endmindmap